env: grid

env_args:
  game_name: "Blocker-v0"
  reward_normalizer: 1.
  state_num: 28

test_nepisode: 32
test_interval: 1000
log_interval: 500
runner_log_interval: 500
learner_log_interval: 500
t_max: 200000
log_all_obs: True